version: "3.8"

services:
  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334" # REST API
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
    driver: local
